name: tattoo
description: "A modern reimplementation of TAT â€” the course helper app for Taipei Tech students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  dio: 5.9.0
  cookie_jar: 4.0.8
  dio_cookie_manager: 3.3.0
  html: 0.15.6
  dio_redirect_interceptor: 1.0.1
  collection: 1.19.1
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: 2.10.1
  freezed: 3.2.3
  json_serializable: 6.11.1
  custom_lint: 0.8.1
  freezed_lint: 0.0.12

flutter:
  uses-material-design: true
  generate: true
