name: tattoo
description: "A modern reimplementation of TAT â€” the course helper app for Taipei Tech students"
publish_to: 'none'

version: 1.0.0+1

environment:
  # TODO: Bump the SDK constraint once the formatting issues are resolved
  # See: https://github.com/dart-lang/dart_style/issues/1785
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  dio: 5.9.1
  cookie_jar: 4.0.8
  dio_cookie_manager: 3.3.0
  html: 0.15.6
  dio_redirect_interceptor: 1.0.1
  collection: 1.19.1
  intl: 0.20.2
  flutter_svg: 2.2.3
  drift: 2.30.1
  drift_flutter: 0.2.8
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: 2.10.5
  drift_dev: 2.30.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
