name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup project
        id: setup
        uses: ./.github/actions/setup-project
        with:
          tools: flutter java

      - name: Verify Flutter version
        if: ${{ steps.setup.outputs.flutter-version != '3.38.9' }}
        run: |
          echo "::error file=.github/workflows/build.yaml::Flutter version has changed to ${{ steps.setup.outputs.flutter-version }}. Please update build.yaml accordingly."
          exit 1

      - name: Setup Gradle cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Android SDK cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
        with:
          key: ${{ runner.os }}-android-sdk-${{ steps.setup.outputs.flutter-version }}
          # Update paths when updating Flutter version
          path: |
            /usr/local/lib/android/sdk/cmake/3.22.1
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Build APK
        run: flutter build apk --debug --no-pub --split-per-abi

      - name: Upload ARM Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: apk-arm-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: apk-arm64-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk

      - name: Upload x64 Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: apk-x64-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-x86_64-debug.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          tools: flutter ruby

      - name: Build iOS
        run: flutter build ios --no-pub --simulator

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: ios-${{ github.sha }}
          path: build/ios/iphonesimulator
